Twins and triplets
Terasology/WildAnimalsGenome pull request #4
Opened 2019-04-22 01:43 UTC by casals

### Contains
Small tweak for allowing twins and triplets upon successful breeding.

### Objective
Start testing mechanisms for probability-based occurrences. In this case, an example of a simple mutation occurs based on a probability table was implemented. Similar structures can be used (i) with Behaviors (so a conjunction of conditions and probabilities can lead to different events) and (ii) with the Engine System (which would determine - expanding this example - if a breeding occurrence would lead to identical or non-identical twins).

### Changes

- `AnimalGeneticsSystem.getSiblings` returns the number of siblings after a successful breedintg event, according to a probability table
- `RandomCollection` implements a simple weighted list

2019-04-22 02:13 UTC, Cervator requested changes
Minor code style tweak requests. I suggest setting up Checkstyle in your IDE that'll flag stuff as per our guidelines :-)

2019-04-22 02:13 UTC, Cervator commented on src/main/java/org/terasology/wildAnimalsGenome/AnimalGeneticsSystem.java
> +        for(int i=0; i <= this.getSiblings(); i++)
Minor code style issue here with whitespace + we always use brackets 👍

2019-04-22 02:13 UTC, Cervator commented on src/main/java/org/terasology/wildAnimalsGenome/AnimalGeneticsSystem.java
> +        rc.add(950,0);
This works fine for a proof of concept 👍 

For a final implementation I would use one of two approaches (or really first the simple one, then the advanced one later):

1) Use constants in the associated System class (so indeed this class) named after each option (so something like `SIBLINGS_NORMAL_PROBABILITY`, `SIBLINGS_TWINS_PROBABILITY` ...)
2) Allow the probabilities to be defined in a prefab, probably with defaults in some associated component class (that way you only have to include the extra numbers when they vary from the default) then loaded when needed

Would this be one place where it would make sense to start at `1` instead of `0` so the value is the number of siblings? :-) Admittedly that would make the for loop start at 1.

2019-04-22 02:13 UTC, Cervator commented on src/main/java/org/terasology/wildAnimalsGenome/util/RandomCollection.java
> +        if (weight <= 0) return this;
More trivial code style issues - brackets & newline 👍

2019-04-22 02:13 UTC, Cervator commented on src/main/java/org/terasology/wildAnimalsGenome/util/RandomCollection.java
> +}
Newline at the end of text files :-)

2019-04-23 14:46 UTC, Cervator approved these changes

2019-04-24 16:40 UTC, jellysnake commented
Can't see any further issues. Merging now

2019-04-24 16:40 UTC, merged